# Generated by Django 2.0 on 2019-02-02 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2019, 2, 2, 12, 34, 9, 503193, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2019, 2, 2, 12, 34, 20, 327657, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
